# Generated by Django 4.1.7 on 2023-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('rollNo', models.IntegerField(max_length=6)),
                ('standard', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentRollNo', models.IntegerField(max_length=6)),
                ('english', models.IntegerField(default=0, max_length=20)),
                ('science', models.IntegerField(default=0, max_length=6)),
                ('maths', models.IntegerField(default=0, max_length=6)),
                ('computer', models.IntegerField(default=0, max_length=6)),
                ('social', models.IntegerField(default=0, max_length=6)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
