# Generated by Django 4.1.7 on 2023-02-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
