# Generated by Django 4.1.7 on 2023-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_id_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
