# Generated by Django 4.1.7 on 2023-02-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='studentRollNo',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
