# Generated by Django 4.1.7 on 2023-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subject_id_alter_subject_studentrollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='field_sum',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
