# Generated by Django 4.1.7 on 2023-02-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subject_field_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
