# Generated by Django 4.1.7 on 2023-02-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subject_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='field_sum',
            new_name='total_marks',
        ),
    ]
